### ISSUE TITLE
Add the three types of habits

### ISSUE THREAD

**Issue by austin-bmitchell15** [austin-bmitchell15/habit-forge#3]
- [ ] General checklist habit
- [ ] Activity habits that have a weekly assignment to them
- [ ] Progressive habit that happen throughout the day
